### ISSUE TITLE
Error with latest vue version (3.4.5) for pro version

### ISSUE THREAD

**Issue by cfab** [banthagroup/fslightbox-vue#91]
Here is the error !

Uncaught (in promise) TypeError: n2[r2] is not a function
    at x (v3.js:1:9330)
    at f2 (v3.js:1:30034)
    at Proxy.<anonymous> (v3.js:1:31997)
    at Proxy.updated (v3.js:1:60202)
    at runtime-core.esm-bundler.js:2861:88
    at callWithErrorHandling (runtime-core.esm-bundler.js:188:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:196:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2841:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:363:40)
    at flushJobs (runtime-core.esm-bundler.js:401:5)

**Comment by alaamebrahim** [comment]
same for me
